version: "3"
services:
    messagebrocker:
      build: /messagebrocker
      ports:
        - 7000:7000
        - 8000:8000
    
    publishers:
      build: /publishers
      depends_on:
        messagebrocker:
          condition: service_started